name: Slack Notification

on:
 push:
 pull_request:
 issues:
   types:
     - opened
     - closed
     - reopened
     - edited
     - deleted
     - pinned
     - unpinned
     - assigned
     - unassigned
     - labeled
     - unlabeled
     - milestoned
     - demilestoned
 issue_comment:
   types: [created, edited, deleted]
 create:
 delete:

jobs:
 notify_slack:
   runs-on: ubuntu-latest
   steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            text: "Custom Field Check",
            attachments: [{
              "author_name": "8398a7@action-slack", // json
              fallback: 'fallback',
              color: 'good',
              title: 'CI Result',
              text: 'Succeeded',
              fields: [{
                title: 'lower case',
                value: 'LOWER CASE CHECK'.toLowerCase(),
                short: true
              },
              {
                title: 'reverse',
                value: 'gnirts esrever'.split('').reverse().join(''),
                short: true
              },
              {
                title: 'long title1',
                value: 'long value1',
                short: false
              }],
              actions: [{
              }]
            }]
          }        
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
